name: TaskManager Test 2

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [21.6.0]

    env:
      MODE: "dev"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.6.0" # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install
     
      - name: Test Code
        run: npm run test
